name: Build/Deploy Air Quality

# Controls when the action will run.
on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *" # every hour

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: Fetch Data
        env:
          WAQI_TOKEN: ${{ secrets.WAQI_TOKEN }}
        run: |
          npm ci
          node ./scripts/fetch-json-data.js
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"	
          git config --local user.name "GitHub Action"	
          git commit -m "Update Air Quality JSON" -a || echo "Nothing to update"
          git push
  build:
    needs: fetch-data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: Build HTML files
        run: |
          npm ci
          node ./scripts/build-html.js
      - name: Commit and push files
        run: |
          git config --local user.email "action@github.com"	
          git config --local user.name "GitHub Action"	
          git commit -m "Build Air Quality HTML" -a || echo "Nothing to update"
          git push
