# This is a basic workflow to help you get started with Actions

name: Update Time

# Controls when the action will run.
on:
  workflow_dispatch:
  schedule:
    - cron: "* * * * *" # every day at midnight

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: Create local changes
        run: |
          echo "test"
          ./scripts/update-times.sh
